### ISSUE TITLE
Error in rake tasks

### ISSUE THREAD

**Issue by cbetta** [teohm/capistrano-shared_file#1]
I am getting errors when running rake tasks in my rails app using this. Using Rails 3.2.8.

Here is the trace:

``` sh
rake -T --trace
rake aborted!
private method `load' called for nil:NilClass
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@puppet/gems/capistrano-shared_file-0.1.1/lib/capistrano/shared_file.rb:5:in `<top (required)>'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in `require'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in `rescue in block in require'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:62:in `block in require'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `each'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `require'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler.rb:128:in `require'
/Users/cbetta/Development/puppet/banana/config/application.rb:7:in `<top (required)>'
/Users/cbetta/Development/puppet/banana/Rakefile:5:in `require'
/Users/cbetta/Development/puppet/banana/Rakefile:5:in `<top (required)>'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/bin/rake:19:in `load'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@global/bin/rake:19:in `<main>'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@puppet/bin/ruby_noexec_wrapper:14:in `eval'
/Users/cbetta/.rvm/gems/ruby-1.9.3-p286@puppet/bin/ruby_noexec_wrapper:14:in `<main>'
```

I had to do this to get rid of the error:

`gem 'capistrano-shared_file', require: nil`

**Comment by stackng** [comment]
+1 I'm getting this error when running rails console.
